### PR TITLE
Nilesh navbar

### PR DESCRIPTION
**Pull request by itsKapri**
navbar color font size is modified

### CODE REVIEW

**Review by chetandivekar — COMMENTED** [review]
Navbar Done | SVG are left

**Review by chetandivekar — COMMENTED** [review]
Navbar done small changes remaining

**Review by chetandivekar — COMMENTED** [review]
Navbar done

**Comment by IAMBHUSHANCHAVAN** [comment]
added

**Review by IAMBHUSHANCHAVAN — APPROVED** [review]
added done by bhushan

**Review by chetandivekar — APPROVED** [review]

**Pull request merged**
